### ISSUE TITLE
Misplacement of LS and typo for MS

### ISSUE THREAD

**Issue by DeployedDev** [GRAMCTRL/remapp.ing#1]
The LS button is misplaced on the remapper and RS should be labelled MS

![Screenshot 2024-11-26 193431](https://github.com/user-attachments/assets/053633d2-ed95-4edc-bacc-5277032ed139)

Here is how it should look like

![Screenshot 2024-11-26 193530](https://github.com/user-attachments/assets/ced0d139-f5b8-4b28-97b1-9df0435ce837)

**Comment by bvoo** [comment]
this _should_ be fixed in https://github.com/GRAMCTRL/remapp.ing/commit/33d938023240da83157626a414fe1962fb9c6b8e. thanks for reporting!
